// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Execute(arg1) {
  return window['go']['gui']['App']['Execute'](arg1);
}

export function BrowseFilePath(arg1) {
  return window['go']['gui']['App']['BrowseFilePath'](arg1);
}

export function BrowseDirectoryPath(arg1) {
  return window['go']['gui']['App']['BrowseDirectoryPath'](arg1);
}
