// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Execute(arg1:Array<string>):Promise<void>;
export function BrowseFilePath(arg1:string):Promise<string>;
export function BrowseDirectoryPath(arg1:string):Promise<string>;
