// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyConfigFileValues(arg1, arg2) {
  return window['go']['app']['App']['ApplyConfigFileValues'](arg1, arg2);
}

export function BrowseDirectoryPath(arg1) {
  return window['go']['app']['App']['BrowseDirectoryPath'](arg1);
}

export function BrowseFilePath(arg1) {
  return window['go']['app']['App']['BrowseFilePath'](arg1);
}

export function Execute(arg1) {
  return window['go']['app']['App']['Execute'](arg1);
}

export function FindConfigFile() {
  return window['go']['app']['App']['FindConfigFile']();
}

export function GetSchema() {
  return window['go']['app']['App']['GetSchema']();
}

export function TerminalResize(arg1, arg2) {
  return window['go']['app']['App']['TerminalResize'](arg1, arg2);
}

export function TerminalWrite(arg1) {
  return window['go']['app']['App']['TerminalWrite'](arg1);
}
