// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ApplyConfigFileValues(arg1:string,arg2:Array<app.ConfigValueUpdate>):Promise<void>;

export function BrowseDirectoryPath(arg1:string):Promise<string>;

export function BrowseFilePath(arg1:string):Promise<string>;

export function Execute(arg1:Array<string>):Promise<void>;

export function FindConfigFile():Promise<string>;

export function GetSchema():Promise<string>;

export function TerminalResize(arg1:number,arg2:number):Promise<void>;

export function TerminalWrite(arg1:string):Promise<void>;
